### PR TITLE
fix(HMS-3850): V2Wizard:use menu toggle for save and build

### LINKED ISSUE #1826: UI mistake- use "Menu toggle" not "split button"
Screenshot 2024-03-20 at 11 56 02 AM
In the review screen where the user an choose to "save" or "save and build" I meant to use a menu toggle WITH AN ACTION, so user can just press "save". Instead in the mocks I used a split action button, where the user is forced to enter the dropdown. Correct version look like the screenshot- https://www.patternfly.org/components/menus/menu-toggle#split-button-toggle-with-action

### PR DESCRIPTION
**Pull request by amirfefer**
This PR fixes #1826 

This PR adds `MenutToggleAction` in the V2 wizard's menu toggle , so instead of clicking twice for save changes, users can just click on the desired action.

https://github.com/osbuild/image-builder-frontend/assets/11807069/29aa37ff-0dd3-4e01-8a16-7233c5f1ae5c

### CODE REVIEW

**Review by lucasgarfield — DISMISSED** [review]
Nice, I love it!

There's a Patternfly pattern for progress indicators in buttons, the spinner usually goes on the left:
https://www.patternfly.org/components/button#progress-indicators

Would you mind tweaking the PR a bit to match the Patternfly example for this?

**Comment by amirfefer** [comment]
Fixed spinner location

File: src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx [hunk 1]
```diff
@@ -41,14 +42,41 @@ const CreateDropdown = ({
...
+  const [createBlueprint, { isLoading }] = useCreateBlueprintMutation({
+    fixedCacheKey: 'createBlueprintKey',
+  });
+  const onSave = async () => {
+    const requestBody = await getBlueprintPayload();
+    setIsOpen(false);
+    requestBody && createBlueprint({ createBlueprintRequest: requestBody });
+  };
+  return (
+    <MenuToggleAction onClick={onSave} id="wizard-create-save-btn">
```
Comment (regexowl) [inline src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx:65]: Looks good! Since there's an ouiaId removed - @jrusz Does pr_check use `ouiaId="wizard-create-save-btn"` anywhere?

Comment (jrusz) [reply src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx:65]: pr_check doesn't run the blueprints test yet and I don't use it yet in my V2 wizard update MR so it's all good :)

Comment (regexowl) [reply src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx:65]: Got it, so we can add it when/if needed. Thank you! :)

**Review by regexowl — APPROVED** [review]
LGTM! :sparkles:

File: src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx (hunk 1 above)
Comment (jrusz) [reply src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx:65]: Yeah I don't need ouiaID for the actual dropdown items, I'd only use it to locate the Dropdown for example, the items are then accessed by their actual names/values.
