### PR TITLE
Wizard: fix blueprint unique name validation in Edit mode

### LINKED ISSUE #2220: Details step is disabled on blueprint edit
When editing a blueprint I can't go to the Details step, I have to walk through the wizard to get there which I believe was not the case before. Also the tests are failing on this as when they get to this step the Next button is disabled.

disabled-step

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Fixes #2220

In cases there is already a state in the wizardSlice, there might have been cases of flicker, when unique request could be started for edit mode, because wizards loads before requestMapper maps the new state of edited blueprints.

In such case, name is not empty (leftover from previous BP create/edit), but wizardMode was not yet set, so defaults to create.

This addresses it by just making sure the validation works as expected in Edit mode.
Now when the name is changed in Edit mode, we run the validation.
We now have the blueprintID in the state, which is empty on create state (might be just easier to recognize mode by id in the future :) )

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Maybe I've actually broken it? we now fire a unique name request in edit mode. Maybe it needs to get mocked? :thinking:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by regexowl** [comment]
> Maybe I've actually broken it? we now fire a unique name request in edit mode. Maybe it needs to get mocked? 🤔

Maybe? But if we are firing a new request, why does it fail in AWS edit mode test only?

**Comment by ezr-ondrej** [comment]
> Maybe? But if we are firing a new request, why does it fail in AWS edit mode test only?

No idea honestly xD but it passes on other PRs (e.g. https://github.com/osbuild/image-builder-frontend/pull/2237).
I'll try to dig a little

File: src/test/fixtures/editMode.ts [hunk 1]
```diff
@@ -248,8 +248,8 @@ export const awsCreateBlueprintRequest: CreateBlueprintRequest = {
 
 export const awsBlueprintResponse: BlueprintResponse = {
   ...awsCreateBlueprintRequest,
-  id: mockBlueprintIds['registration'],
-  description: mockBlueprintDescriptions['registration'],
+  id: mockBlueprintIds['aws'],
+  description: mockBlueprintDescriptions['aws'],
```
Comment (ezr-ondrej) [inline src/test/fixtures/editMode.ts:252]: Hehe this was the culprit :stuck_out_tongue:
We loaded wrong id on the blueprint get request and then we were assuming the aws blueptintID is different then what the unique request was returning and failing to allow saving the changes :)

Comment (regexowl) [reply src/test/fixtures/editMode.ts:252]: That was probably my doing :face_with_peeking_eye: :sweat_smile: Thanks for digging into it!! :bug:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by regexowl — APPROVED** [review]
Thank you! Let's merge this next to unblock @jrusz
